chore: adding BP 03

diff --git a/.cloudbees/workflows/bp-tf-ci.yaml b/.cloudbees/workflows/bp-tf-ci.yaml
--- a/.cloudbees/workflows/bp-tf-ci.yaml
+++ b/.cloudbees/workflows/bp-tf-ci.yaml
@@ -282,3 +282,110 @@ jobs:
           --username k8s-admin-rol \
           --group system:masters
         kubectl describe configmap aws-auth -n kube-system
+  
+  bp03:
+    env:
+      # Stages
+      # CI: deploy,validate,destroy
+      # Troubleshooting: deploy,validate,onboarding
+      # Nuke (Delete Dangling resource): wipeout
+      STAGES: "deploy,validate,destroy"
+      ROOT: 03-at-scale-k
+      TF_VAR_hosted_zone: bp03-ci.aws.ps.beescloud.com
+    needs:
+      - init
+    steps:
+
+    - name: Configure AWS Credentials
+      uses: cloudbees-io/configure-aws-credentials@v1
+      with:
+        aws-region: ${{ env.TF_VAR_aws_region }}
+        aws-access-key-id: ${{ secrets.AWS_TF_CBCI_EKS_AccessKeyID }}
+        aws-secret-access-key: ${{ secrets.AWS_TF_CBCI_EKS_SecretAccessKey }}
+        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
+        role-external-id: cloudbees
+        role-duration-seconds: "3600"
+
+    - name: Checkout code
+      uses: cloudbees-io/checkout@v1
+
+    - name: 03-at-scale-k - Set
+      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
+      shell: bash
+      run : |
+        cat <<EOT >> blueprints/${{ env.ROOT }}/.auto.tfvars
+        ${{ env.TF_AUTO_VARS_FILE }}
+        EOT
+        cat blueprints/${{ env.ROOT }}/.auto.tfvars
+        cat <<EOT >> blueprints/${{ env.ROOT }}/backend.tf
+        terraform {
+          backend "s3" {
+            bucket = "${{ env.BUCKET_NAME_TF_STATE }}"
+            key    = "${{ env.ROOT }}/ci/terraform.tfstate"
+            region = "${{ env.AWS_REGION_TF_BUCKET }}"
+          }
+        }
+        EOT
+        echo "Environment Variables:"
+        printenv
+
+    - name: 03-at-scale-k - Deploy
+      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
+      if: contains(env.STAGES, 'deploy')
+      kind: build
+      shell: bash
+      run : |
+        set -x
+        # It Resolves Issue #66
+        aliases=("alias/eks/cbci-bp02-${{ env.TF_VAR_suffix }}-eks" "alias/eks/cbci-bp02-${{ env.TF_VAR_suffix }}")
+        for alias in "${aliases[@]}"; do
+          aws kms delete-alias \
+          --alias-name $alias \
+          --region ${{ env.TF_VAR_aws_region }} || echo "$alias does not exist"
+        done
+        CI=true make deploy
+        aws s3api put-object \
+          --bucket "${{ env.BUCKET_NAME_TF_STATE }}" \
+          --region "${{ env.AWS_REGION_TF_BUCKET }}" \
+          --body blueprints/${{ env.ROOT }}/terraform.output \
+          --key ${{ env.ROOT }}/ci/${{ env.ROOT }}.terraform.output || echo "Failed to put $body object in ${{ env.BUCKET_NAME_TF_STATE }}"
+
+    - name: 03-at-scale-k - Validate
+      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
+      if: contains(env.STAGES, 'validate')
+      kind: test
+      shell: bash
+      run : |
+        CI=true make validate
+
+    - name: 03-at-scale-k - Destroy
+      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
+      if: contains(env.STAGES, 'destroy')
+      shell: bash
+      run : |
+        CI=true make destroy
+
+    - name: 03-at-scale-k - Wipeout
+      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
+      if: contains(env.STAGES, 'wipeout')
+      shell: bash
+      run : |
+        terraform -chdir=blueprints/${{ env.ROOT }} init -reconfigure && CI=true make destroy
+
+    - name: 03-at-scale-k - Role Onboarding
+      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
+      if: contains(env.STAGES, 'onboarding')
+      env:
+        TARGET_ROLE: arn:aws:iam::324005994172:role/AWSReservedSSO_infra-admin_256addbf79cfacd1
+      shell: bash
+      run : |
+        set -x
+        cd blueprints/${{ env.ROOT }} && eval $(terraform output --raw kubeconfig_export)
+        kubectl describe configmap aws-auth -n kube-system
+        eksctl create iamidentitymapping \
+          --cluster $(terraform output --raw eks_cluster_name) \
+          --region ${{ env.TF_VAR_aws_region }} \
+          --arn ${{ env.TARGET_ROLE }} \
+          --username k8s-admin-rol \
+          --group system:masters
+        kubectl describe configmap aws-auth -n kube-system
